### ISSUE TITLE
[Question] I was wondering how accurate is the battery SoC tracking with voltage measurement technique.

### ISSUE THREAD

**Issue by Nickobellic15X** [ovidiu4/smart-plant-monitor#1]
Because we know that the battery voltage drops drastically when under load, so a full charge battery tested under open circuit condition may show anywhere between 4 and 4.2v but as soon as you connect it to a circuit, it will drop to 3.8V or so...

Are you compensating this in code?

**Comment by ovidiu4** [comment]
To be honest I don't think that's necessary for this device. 
It is only measuring the voltage under load which is what matters. 
Otherwise, due to voltage drop like you said, when the battery is close to 3.4V with no load, it might cause a processor brownout when booting
